
 apiVersion: v1
 kind: Service
 metadata:
   name: hello-world
   labels:
     app: hrllo-world
   annotations:
     dev.okteto.com/auto-ingress: "true"  
 spec:
   type: ClusterIP 
   ports:
     - port: 8080
       protocol: TCP
       targetPort: 8080
       
   selector:
     app: hello-world
